### ISSUE TITLE
Language lab issue

### ISSUE THREAD

**Issue by Laastine** [Laastine/lukkarimaatti#41]
Language lab courses doesn't shows different group letter (A,B,C,D) in course listing and calendar view. Number of occurrences is also incorrectly.

**Comment by OdeGitHub** [comment]
Can you clarify this problem. In beta environment course group letters seems to work for courses 
"Technical English Reading Course: D", "Teknisk svenska: D", "Industrial Economy in China: A" at least .
![image](https://cloud.githubusercontent.com/assets/2425787/5813263/7497cba0-a083-11e4-9772-43b755894917.png)

**Comment by Laastine** [comment]
![error](https://cloud.githubusercontent.com/assets/2429604/5813752/573ead78-a08b-11e4-8440-ce4bdd50590b.png)
See attachment above. I search Saksan jatkokurssi group A and result is quite different.

**Comment by Laastine** [comment]
Backend now provides info about group letter. 
```{"courseId":-7494743250797182688,"courseCode":"FV12A1410","courseName":"Saksan jatkokurssi 1: D","period":"","weekNumber":"17","weekDay":"ti","timeOfDay":"9-13","classroom":"1487","type":"","department":"kike","teacher":"Rantonen, Pirjo","misc":"�","groupName":"D"}```
Frontend could now implement separation of the groups.

**Comment by Laastine** [comment]
Fixed, See commit 9469a2c. Language lab course now have groupLetter property when adding new one to timetable. Change is backward combatible with email links, but new links are generated with group letter e.g. FV12A1210 - Saksan peruskurssi 1: D -> old: ?FV12A1210, new ?FV12A1210&D.
